steps:
  integrationArtifactDeploy:
    cpiApiServiceKeyCredentialsId: cpisuite-us-04
    integrationFlowId: S0023221132-flow4
  integrationArtifactGetMplStatus:
    cpiApiServiceKeyCredentialsId: cpisuite-us-04
    integrationFlowId: S0023221132-flow4
  integrationArtifactUpload:
    cpiApiServiceKeyCredentialsId: cpisuite-us-04
    integrationFlowId: S0023221132-flow4
    integrationFlowName: S0023221132-flow4
    packageId: CICD
    filePath: S0023221132-flow4.zip